### PR TITLE
Tighten Up reward and staking displays

### PR DESCRIPTION
**Pull request by aaronmgdr**
1. Sometimes rewards end when this happens it would say 0 TOKENS / Week. now this skips except for the earned/unclaimed if the zero rewards tokens still has unclaimed rewards. 
2. If earned amount is less than 0.0001 tokens display more digits rather than rounding down to zero 
3. when displaying staked amounts show sigificant digits when amount is less than one, and 1 decimals when 1 < x < 10.

# examples 
Screen Shot 2021-12-04 at 1 32 37 PM
Screen Shot 2021-12-04 at 1 32 42 PM

Screen Shot 2021-12-04 at 1 24 58 PM

### CODE REVIEW

**Comment by BriungRi** [comment]
Screen Shot 2021-12-03 at 8 12 00 PM

**Comment by BriungRi** [comment]
CELO seems to still show
Screen Shot 2021-12-03 at 8 12 00 PM

**Comment by aaronmgdr** [comment]
well well having low rewards but not no rewards seems to be the issue. In a way this means we found a new bug people could be leaving $$ on the table thinking its zero.

I think solution would be if its less than 0.0001 to display as < 0.0001 rather than 0.000

**Review by BriungRi — APPROVED** [review]

**Comment by BriungRi** [comment]
Is this on latest master? If not, can we rebase it onto latest master? I can't view the farm details rn because of a bug that should now be fixed on master.

**Pull request merged**
